"""add favorites table

Revision ID: 47618b13ebd4
Revises: 
Create Date: 2026-03-02 09:24:22.632367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47618b13ebd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_movie_tmdb_id', ['tmdb_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.create_unique_constraint(None, ['password_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_user_username', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint('uq_movie_tmdb_id', type_='unique')

    # ### end Alembic commands ###
