"""Initial Migration

Revision ID: 916e1895b591
Revises: 
Create Date: 2026-02-26 10:02:01.097565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916e1895b591'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['password_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
